In [4]:
## pytorch tutorial #! 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [5]:
from __future__ import print_function
import torch

In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[1.6189e-37, 0.0000e+00, 6.0256e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.8617e+25, 1.3342e+31, 7.1103e-04],
        [1.8319e+25, 5.0834e+31, 3.2605e-12],
        [7.5555e+31, 7.0736e+31, 1.8037e+28]])


In [7]:
x = torch.tensor([5, 3])
print(x)

tensor([5, 3])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x=torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3907, -0.0340, -0.0068],
        [-2.0205,  0.1402,  0.1078],
        [-1.5552,  1.1430, -0.6581],
        [ 0.7724,  0.4268, -0.2739],
        [-1.5204,  1.0201, -0.7330]])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.7342,  0.2436,  0.6171],
        [-1.7266,  0.5524,  0.3546],
        [-1.1419,  1.7268, -0.0031],
        [ 0.9584,  1.2754,  0.2105],
        [-0.5752,  1.8431, -0.2206]])


In [10]:
print(torch.add(x, y))

tensor([[ 0.7342,  0.2436,  0.6171],
        [-1.7266,  0.5524,  0.3546],
        [-1.1419,  1.7268, -0.0031],
        [ 0.9584,  1.2754,  0.2105],
        [-0.5752,  1.8431, -0.2206]])


In [11]:
result = torch.empty(4, 3)
print(result)
torch.add(x, y, out=result)
print(result)
# addition will change result 

tensor([[1.5604e-37, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


tensor([[ 0.7342,  0.2436,  0.6171],
        [-1.7266,  0.5524,  0.3546],
        [-1.1419,  1.7268, -0.0031],
        [ 0.9584,  1.2754,  0.2105],
        [-0.5752,  1.8431, -0.2206]])

tensor([[ 0.7342,  0.2436,  0.6171],
        [-1.7266,  0.5524,  0.3546],
        [-1.1419,  1.7268, -0.0031],
        [ 0.9584,  1.2754,  0.2105],
        [-0.5752,  1.8431, -0.2206]])


In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [14]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [15]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y 
    print(z)
    print(z.to("cpu", torch.double))

tensor([[ 1.3612, -0.8975,  1.4291,  1.0989],
        [ 1.3444, -0.2823,  0.8402,  1.4723],
        [ 0.3635,  0.1028,  0.7017,  1.8582],
        [ 1.0877,  0.3051, -0.3926,  1.2543]], device='cuda:0')
tensor([[ 1.3612, -0.8975,  1.4291,  1.0989],
        [ 1.3444, -0.2823,  0.8402,  1.4723],
        [ 0.3635,  0.1028,  0.7017,  1.8582],
        [ 1.0877,  0.3051, -0.3926,  1.2543]], dtype=torch.float64)
